package ke.ac.mku.authcore.bootstrap

import ke.ac.mku.authcore.contracts.session.SessionWarning
import ke.ac.mku.authcore.recovery.CircuitBreakerState
import ke.ac.mku.authcore.recovery.RecoveryStrategy
import ke.ac.mku.authcore.state.AuthenticationState
import ke.ac.mku.authcore.state.RuntimeState

sealed class BootstrapEvent {
    // --- PLATFORM LIFECYCLE ---
    object BootstrapStarted : BootstrapEvent()
    object ConfigurationLoaded : BootstrapEvent()
    object ConfigurationValidated : BootstrapEvent()
    object AuthenticationCoreInitialized : BootstrapEvent()
    object DependenciesResolved : BootstrapEvent()
    object BootstrapCompleted : BootstrapEvent()
    data class BootstrapFailed(val error: String) : BootstrapEvent()

    // --- PLATFORM VERIFICATION (FINAL-001) ---
    object PlatformValidationStarted : BootstrapEvent()
    data class PlatformValidationStepCompleted(val step: Int, val name: String) : BootstrapEvent()
    data class PlatformValidationFailed(val step: Int, val reason: String) : BootstrapEvent()
    object PlatformValidationCompleted : BootstrapEvent()
    object DashboardLaunchStarted : BootstrapEvent()

    // --- SERVICE REGISTRY (CORE-005) ---
    object RegistryReady : BootstrapEvent()
    data class ServiceRegistered(val serviceName: String) : BootstrapEvent()
    data class ServiceResolved(val serviceName: String) : BootstrapEvent()
    data class ServiceRegistrationFailed(val serviceName: String, val error: String) : BootstrapEvent()

    // --- SECURITY RESILIENCE (SECURITY-002) ---
    data class KeystoreOperationRetried(val attempt: Int) : BootstrapEvent()
    object KeystoreRecovered : BootstrapEvent()
    data class KeystoreRecoveryFailed(val reason: String) : BootstrapEvent()

    // --- STATE REGISTRY (CORE-007) ---
    object StateInitialized : BootstrapEvent()
    data class StateChanged(val previous: RuntimeState, val current: RuntimeState) : BootstrapEvent()
    object StateRestored : BootstrapEvent()
    object StateReset : BootstrapEvent()
    data class StateValidationFailed(val reason: String) : BootstrapEvent()

    // --- FEATURE REGISTRY (CORE-008) ---
    data class FeatureRegistered(val featureId: String) : BootstrapEvent()
    data class FeatureEnabled(val featureId: String) : BootstrapEvent()
    data class FeatureDisabled(val featureId: String) : BootstrapEvent()
    object FeatureRegistryReady : BootstrapEvent()
    data class FeatureValidationFailed(val featureId: String, val reason: String) : BootstrapEvent()

    // --- RUNTIME ENVIRONMENT (CORE-009) ---
    object RuntimeInitialized : BootstrapEvent()
    object RuntimeReady : BootstrapEvent()
    object RuntimeShutdown : BootstrapEvent()
    data class ResourceWarning(val message: String) : BootstrapEvent()
    object MemoryPressureDetected : BootstrapEvent()
    data class RuntimeFailure(val error: String) : BootstrapEvent()

    // --- HEALTH & MONITORING (CORE-010) ---
    object HealthMonitorReady : BootstrapEvent()
    object HealthStatusChanged : BootstrapEvent()
    data class ComponentFailed(val component: String) : BootstrapEvent()
    data class ComponentRecovered(val component: String) : BootstrapEvent()
    object MemoryWarning : BootstrapEvent()
    object CpuWarning : BootstrapEvent()
    object NetworkWarning : BootstrapEvent()
    object AuthenticationWarning : BootstrapEvent()
    object RuntimeWarning : BootstrapEvent()
    object CriticalFailure : BootstrapEvent()
    object DiagnosticReportGenerated : BootstrapEvent()

    // --- RECOVERY MANAGER (CORE-011) ---
    object RecoveryManagerReady : BootstrapEvent()
    data class RecoveryStarted(val serviceName: String, val strategy: RecoveryStrategy, val attempt: Int) : BootstrapEvent()
    data class RecoveryCompleted(val serviceName: String, val strategy: RecoveryStrategy, val durationMs: Long) : BootstrapEvent()
    data class RecoveryFailed(val serviceName: String, val strategy: RecoveryStrategy, val error: String, val attempts: Int) : BootstrapEvent()
    data class ServiceRestartRequested(val serviceName: String) : BootstrapEvent()
    data class ServiceRestarted(val serviceName: String) : BootstrapEvent()
    data class ReinitializeServiceRequested(val serviceName: String) : BootstrapEvent()
    data class RollbackRequested(val serviceName: String) : BootstrapEvent()
    object RollbackCompleted : BootstrapEvent()
    data class RetryStarted(val serviceName: String, val attempt: Int, val maxAttempts: Int) : BootstrapEvent()
    data class RetryFailed(val serviceName: String, val error: String, val attempts: Int) : BootstrapEvent()
    data class CircuitOpened(val serviceName: String) : BootstrapEvent()
    data class CircuitClosed(val serviceName: String) : BootstrapEvent()
    object SystemRecovered : BootstrapEvent()
    data class CircuitStateChanged(val serviceName: String, val previousState: CircuitBreakerState, val newState: CircuitBreakerState) : BootstrapEvent()

    // --- SECURITY (SECURITY-003/004/005) ---
    object SecureStorageReady : BootstrapEvent()
    object CryptoManagerReady : BootstrapEvent()
    object TrustManagerReady : BootstrapEvent()
    object SecurityMonitorReady : BootstrapEvent()
    object ThreatDetectorReady : BootstrapEvent()
    object SecurityPlatformReady : BootstrapEvent()
    object SecurityValidationCompleted : BootstrapEvent()
    data class StorageInitialized(val domain: String) : BootstrapEvent()
    data class DataStored(val domain: String, val key: String) : BootstrapEvent()
    data class DataRetrieved(val domain: String, val key: String, val success: Boolean) : BootstrapEvent()
    data class DataDeleted(val domain: String, val key: String) : BootstrapEvent()
    data class StorageCleared(val domain: String, val count: Int) : BootstrapEvent()
    data class IntegrityVerified(val domain: String, val key: String) : BootstrapEvent()
    data class IntegrityFailed(val domain: String, val key: String) : BootstrapEvent()
    data class StorageFailure(val domain: String, val error: String) : BootstrapEvent()
    data class CacheExpired(val key: String, val ttlMs: Long) : BootstrapEvent()
    data class CertificateVerified(val host: String, val fingerprint: String) : BootstrapEvent()
    data class CertificateValidationFailed(val host: String, val error: String, val status: String) : BootstrapEvent()
    data class CertificatePinVerified(val host: String) : BootstrapEvent()
    data class CertificatePinFailed(val host: String, val expectedPin: String, val actualPin: String) : BootstrapEvent()
    data class TrustViolationDetected(val host: String, val violation: String) : BootstrapEvent()
    data class SecureConnectionEstablished(val host: String, val tlsVersion: String) : BootstrapEvent()
    data class TlsHandshakeCompleted(val host: String, val success: Boolean, val durationMs: Long) : BootstrapEvent()
    data class ThreatDetected(val category: String, val level: String) : BootstrapEvent()
    data class SecurityWarning(val message: String, val level: String) : BootstrapEvent()
    data class SecurityIncidentCreated(val incidentId: String, val level: String, val description: String) : BootstrapEvent()
    object PlatformIntegrityVerified : BootstrapEvent()
    data class IntegrityFailure(val details: String) : BootstrapEvent()
    data class AuditRecorded(val count: Int) : BootstrapEvent()
    object SecurityScanCompleted : BootstrapEvent()
    data class SecurityReportGenerated(val healthScore: Float, val threatCount: Int) : BootstrapEvent()

    // --- AUTHENTICATION (AUTH-001/002/003) ---
    object AuthenticationStarted : BootstrapEvent()
    data class AuthenticationProcessing(val step: String) : BootstrapEvent()
    data class AuthenticationSuccess(val regNumber: String, val studentName: String?) : BootstrapEvent()
    data class AuthenticationFailed(val reason: String, val errorCode: String?) : BootstrapEvent()
    object AuthenticationCancelled : BootstrapEvent()
    data class AuthenticationRetrying(val attemptNumber: Int, val maxAttempts: Int) : BootstrapEvent()
    object AuthenticationCompleted : BootstrapEvent()
    object LoginWorkflowStarted : BootstrapEvent()
    data class LoginWorkflowProcessing(val step: String) : BootstrapEvent()
    data class LoginAuthenticated(val regNumber: String) : BootstrapEvent()
    data class LoginSessionCreated(val regNumber: String, val portalType: String = "student") : BootstrapEvent()
    data class LoginPortalConnected(val portalUrl: String) : BootstrapEvent()
    data class LoginCompleted(val regNumber: String) : BootstrapEvent()
    data class LoginFailed(val reason: String, val errorCode: String?) : BootstrapEvent()
    object LoginCancelled : BootstrapEvent()
    object LogoutCompleted : BootstrapEvent()
    object AuthenticationStateInitialized : BootstrapEvent()
    data class AuthenticationStateChanged(val previous: AuthenticationState, val current: AuthenticationState) : BootstrapEvent()
    data class AuthenticationStateRestored(val state: AuthenticationState) : BootstrapEvent()
    data class AuthenticationStatePersisted(val state: AuthenticationState) : BootstrapEvent()
    data class AuthenticationStateExpired(val previousState: AuthenticationState) : BootstrapEvent()
    data class AuthenticationStateFailed(val reason: String) : BootstrapEvent()
    data class AuthenticationStateRecovered(val recoveredState: AuthenticationState) : BootstrapEvent()
    object AuthenticationReady : BootstrapEvent()

    // --- SESSION & COOKIES (SESSION-001/002/003, COOKIE-001/002) ---
    object SessionCreating : BootstrapEvent()
    data class SessionCreated(val portalType: String = "student") : BootstrapEvent()
    object SessionRestoring : BootstrapEvent()
    object SessionRestored : BootstrapEvent()
    object SessionRefreshing : BootstrapEvent()
    object SessionRefreshed : BootstrapEvent()
    object SessionValidating : BootstrapEvent()
    object SessionExpiring : BootstrapEvent()
    object SessionExpired : BootstrapEvent()
    object SessionTerminating : BootstrapEvent()
    object SessionTerminated : BootstrapEvent()
    data class SessionFailed(val reason: String) : BootstrapEvent()
    object SessionRecovered : BootstrapEvent()
    object SessionValidationStarted : BootstrapEvent()
    object SessionValidationPassed : BootstrapEvent()
    data class SessionValidationWarning(val warnings: List<SessionWarning>) : BootstrapEvent()
    data class SessionValidationFailed(val reason: String) : BootstrapEvent()
    object SessionIntegrityVerified : BootstrapEvent()
    data class SessionIntegrityFailed(val reason: String) : BootstrapEvent()
    object SessionExpiredDetected : BootstrapEvent()
    object SessionRecoveryRequired : BootstrapEvent()
    object SessionValidatorReady : BootstrapEvent()
    object ApplicationRestarted : BootstrapEvent()
    object NetworkRecovered : BootstrapEvent()
    object DeviceUnlocked : BootstrapEvent()
    object ApplicationCrashed : BootstrapEvent()
    object ProcessRecreated : BootstrapEvent()
    object RecoveryRequested : BootstrapEvent()
    object SessionRecoveryStarted : BootstrapEvent()
    object SessionBackupLoaded : BootstrapEvent()
    object SessionRestorationStarted : BootstrapEvent()
    object SessionRestoredFromBackup : BootstrapEvent()
    object SessionReauthenticated : BootstrapEvent()
    object SessionRecoveryCompleted : BootstrapEvent()
    data class SessionRecoveryFailed(val reason: String, val attempts: Int) : BootstrapEvent()
    object SessionRecreated : BootstrapEvent()
    object SessionRecoveryAborted : BootstrapEvent()
    object SessionPlatformReady : BootstrapEvent()
    data class CookieCreated(val name: String) : BootstrapEvent()
    data class CookieUpdated(val name: String) : BootstrapEvent()
    data class CookieDeleted(val name: String) : BootstrapEvent()
    data class CookieExpired(val name: String) : BootstrapEvent()
    data class CookieValidationStarted(val name: String) : BootstrapEvent()
    data class CookieValidationPassed(val name: String) : BootstrapEvent()
    data class CookieValidationFailed(val name: String, val reason: String) : BootstrapEvent()
    object CookieStoreCleared : BootstrapEvent()
    object CookieManagerReady : BootstrapEvent()
    object CookieSynchronizationStarted : BootstrapEvent()
    object CookieSynchronizationCompleted : BootstrapEvent()
    data class CookieSynchronizationFailed(val reason: String) : BootstrapEvent()
    data class CookieConflictDetected(val conflicts: Int) : BootstrapEvent()
    object CookieConflictResolved : BootstrapEvent()
    object CookieConsistencyVerified : BootstrapEvent()
    object CookiePlatformReady : BootstrapEvent()

    // --- NETWORK & PIPELINE (NETWORK-001/003/004) ---
    object NetworkReady : BootstrapEvent()
    object RequestPipelineReady : BootstrapEvent()
    object ResponseReceived : BootstrapEvent()
    object ResponseProcessed : BootstrapEvent()
    object NetworkPlatformReady : BootstrapEvent()
    object NetworkInitializing : BootstrapEvent()
    object NetworkOnline : BootstrapEvent()
    object NetworkOffline : BootstrapEvent()
    object NetworkConnecting : BootstrapEvent()
    object NetworkDisconnected : BootstrapEvent()
    object NetworkRecoveryStarted : BootstrapEvent()
    object NetworkRecoveryCompleted : BootstrapEvent()
    data class NetworkFailed(val reason: String) : BootstrapEvent()
    object RequestReceived : BootstrapEvent()
    object RequestValidated : BootstrapEvent()
    object RequestEnriched : BootstrapEvent()
    object RequestSigned : BootstrapEvent()
    object RequestReady : BootstrapEvent()
    data class PipelineValidationFailed(val reason: String) : BootstrapEvent()
    data class PipelineExecutionFailed(val reason: String) : BootstrapEvent()
    object AuthenticationNetworkReady : BootstrapEvent()
    data class ResponseFailed(val reason: String) : BootstrapEvent()
    object ResponseValidated : BootstrapEvent()
    object CookiesUpdated : BootstrapEvent()
    object SessionUpdated : BootstrapEvent()
    object NetworkConnected : BootstrapEvent()
    object ApplicationResumed : BootstrapEvent()

    // --- PORTAL DISCOVERY & CHANGE MONITOR (PORTAL-001/002/003/004/005) ---
    object PortalDiscoveryStarted : BootstrapEvent()
    object PortalDiscoveryCompleted : BootstrapEvent()
    object NavigationDiscoveryStarted : BootstrapEvent()
    object NavigationDiscoveryCompleted : BootstrapEvent()
    object RequestDiscoveryStarted : BootstrapEvent()
    object RequestDiscoveryCompleted : BootstrapEvent()
    object PortalMonitorStarted : BootstrapEvent()
    object PortalReady : BootstrapEvent()
    object PortalPlatformReady : BootstrapEvent()
    object PortalInitializing : BootstrapEvent()
    object PortalConnecting : BootstrapEvent()
    object PortalConnected : BootstrapEvent()
    object PortalAuthenticated : BootstrapEvent()
    object PortalDisconnected : BootstrapEvent()
    object PortalReconnecting : BootstrapEvent()
    data class PortalConnectionFailed(val reason: String) : BootstrapEvent()
    object PortalMappingStarted : BootstrapEvent()
    object PortalMappingCompleted : BootstrapEvent()
    data class PortalMappingFailed(val reason: String) : BootstrapEvent()
    data class DomainModelCreated(val modelName: String) : BootstrapEvent()
    data class SchemaValidationFailed(val reason: String) : BootstrapEvent()
    object PortalMapperReady : BootstrapEvent()
    object PortalSyncStarted : BootstrapEvent()
    object PortalSyncCompleted : BootstrapEvent()
    data class PortalSyncFailed(val reason: String) : BootstrapEvent()
    object PortalConflictDetected : BootstrapEvent()
    object PortalConflictResolved : BootstrapEvent()
    object PortalStateUpdated : BootstrapEvent()
    object PortalConsistencyVerified : BootstrapEvent()
    data class PortalPageDiscovered(val url: String) : BootstrapEvent()
    object PortalNavigationDiscovered : BootstrapEvent()
    data class PortalModuleDiscovered(val name: String) : BootstrapEvent()
    object PortalMapUpdated : BootstrapEvent()
    data class PortalDiscoveryFailed(val reason: String) : BootstrapEvent()
    data class NavigationNodeDiscovered(val label: String, val url: String) : BootstrapEvent()
    data class MenuDiscovered(val label: String) : BootstrapEvent()
    object NavigationGraphUpdated : BootstrapEvent()
    data class NavigationDiscoveryFailed(val reason: String) : BootstrapEvent()
    data class PortalVersionChanged(val oldVersion: String, val newVersion: String) : BootstrapEvent()
    object PortalStructureChanged : BootstrapEvent()
    object PortalNavigationChanged : BootstrapEvent()
    object PortalEndpointChanged : BootstrapEvent()
    object PortalSchemaChanged : BootstrapEvent()
    object PortalRediscoveryStarted : BootstrapEvent()
    object PortalRediscoveryCompleted : BootstrapEvent()
    object PortalAdaptationCompleted : BootstrapEvent()
    data class PortalMonitorFailed(val error: String) : BootstrapEvent()

    // --- ENDPOINT MANAGEMENT (ENDPOINT-001/002) ---
    object EndpointDiscoveryStarted : BootstrapEvent()
    object EndpointDiscoveryCompleted : BootstrapEvent()
    data class EndpointValidationFailed(val identifier: String, val reason: String) : BootstrapEvent()
    data class EndpointRegistered(val identifier: String) : BootstrapEvent()
    object EndpointCacheUpdated : BootstrapEvent()
    object EndpointRegistryReady : BootstrapEvent()
    object EndpointHealthCheckStarted : BootstrapEvent()
    data class EndpointHealthy(val identifier: String) : BootstrapEvent()
    data class EndpointDegraded(val identifier: String, val latencyMs: Long) : BootstrapEvent()
    data class EndpointUnreachable(val identifier: String) : BootstrapEvent()
    data class EndpointRecovered(val identifier: String) : BootstrapEvent()
    data class EndpointFailed(val identifier: String, val reason: String) : BootstrapEvent()
    data class CertificateExpiring(val identifier: String, val daysRemaining: Int) : BootstrapEvent()
    data class FailoverInitiated(val identifier: String, val newEndpoint: String) : BootstrapEvent()
    object AuthenticationPlatformReady : BootstrapEvent()

    // --- REQUEST DISCOVERY (PORTAL-004) ---
    data class EndpointDiscovered(val method: String, val url: String) : BootstrapEvent()
    data class RequestCaptured(val requestId: String) : BootstrapEvent()
    data class CsrfTokenDiscovered(val tokenName: String) : BootstrapEvent()
    object RequestRegistryUpdated : BootstrapEvent()

    // --- SEMANTIC LAYER (PROGRAM-006/007/008/009/010) ---
    object DomAnalysisStarted : BootstrapEvent()
    object DocumentParsed : BootstrapEvent()
    object SemanticDomCreated : BootstrapEvent()
    data class TablesDetected(val count: Int) : BootstrapEvent()
    data class FormsDetected(val count: Int) : BootstrapEvent()
    data class CardsDetected(val count: Int) : BootstrapEvent()
    object DomAnalysisCompleted : BootstrapEvent()
    data class DomAnalysisFailed(val reason: String) : BootstrapEvent()
    object SemanticClassificationStarted : BootstrapEvent()
    data class EntityClassified(val id: String, val type: String, val confidence: Float) : BootstrapEvent()
    data class UnknownEntityDetected(val details: String) : BootstrapEvent()
    object ClassificationCompleted : BootstrapEvent()
    object SemanticRegistryUpdated : BootstrapEvent()
    data class ClassificationFailed(val reason: String) : BootstrapEvent()
    object JsonGenerationStarted : BootstrapEvent()
    data class SchemaGenerated(val domain: String) : BootstrapEvent()
    data class EntitySerialized(val entityId: String) : BootstrapEvent()
    object JsonValidated : BootstrapEvent()
    object NormalizedJsonCreated : BootstrapEvent()
    object DashboardDatasetCreated : BootstrapEvent()
    object JsonValidationCompleted : BootstrapEvent()
    object PortalJsonReady : BootstrapEvent()
    object JsonGenerationCompleted : BootstrapEvent()
    data class JsonGenerationFailed(val reason: String) : BootstrapEvent()
    object RelationshipEngineStarted : BootstrapEvent()
    data class EntityLinked(val sourceId: String, val targetId: String, val type: String) : BootstrapEvent()
    data class RelationshipCreated(val relationshipId: String, val confidence: Float) : BootstrapEvent()
    object GraphUpdated : BootstrapEvent()
    object GraphValidated : BootstrapEvent()
    object RelationshipEngineCompleted : BootstrapEvent()
    data class RelationshipEngineFailed(val reason: String) : BootstrapEvent()
    object KnowledgeGraphStarted : BootstrapEvent()
    data class KnowledgeNodeCreated(val entityId: String) : BootstrapEvent()
    data class KnowledgeEdgeCreated(val sourceId: String, val targetId: String) : BootstrapEvent()
    object ReasoningCompleted : BootstrapEvent()
    object KnowledgeGraphUpdated : BootstrapEvent()
    object StudentContextSeedReady : BootstrapEvent()
    object KnowledgeGraphCompleted : BootstrapEvent()
    data class KnowledgeGraphFailed(val reason: String) : BootstrapEvent()

    // --- CONTEXT LAYER (PROGRAM-011/012/013/014/015) ---
    object StudentContextStarted : BootstrapEvent()
    object StudentContextUpdated : BootstrapEvent()
    object AcademicContextChanged : BootstrapEvent()
    object FinancialContextChanged : BootstrapEvent()
    object LearningContextChanged : BootstrapEvent()
    object PriorityChanged : BootstrapEvent()
    object StudentContextReady : BootstrapEvent()
    data class StudentContextFailed(val reason: String) : BootstrapEvent()
    object ContextSyncStarted : BootstrapEvent()
    data class ContextDeltaDetected(val domains: List<String>) : BootstrapEvent()
    object ContextUpdated : BootstrapEvent()
    object DashboardDeltaReady : BootstrapEvent()
    object ContextSyncCompleted : BootstrapEvent()
    data class ContextSyncFailed(val reason: String) : BootstrapEvent()
    object ContextCacheStarted : BootstrapEvent()
    data class SnapshotCreated(val snapshotId: String) : BootstrapEvent()
    object ContextCached : BootstrapEvent()
    object OfflineContextLoaded : BootstrapEvent()
    data class CacheRestored(val snapshotId: String) : BootstrapEvent()
    object CacheCleanupCompleted : BootstrapEvent()
    object ContextCacheCompleted : BootstrapEvent()
    data class ContextCacheFailed(val reason: String) : BootstrapEvent()
    object ContextValidationStarted : BootstrapEvent()
    object ValidationCompleted : BootstrapEvent()
    data class ValidationWarning(val domain: String, val reason: String) : BootstrapEvent()
    data class ContextRepaired(val action: String) : BootstrapEvent()
    object DashboardContextReady : BootstrapEvent()
    object LayerThreeCompleted : BootstrapEvent()
    data class ContextValidationFailed(val reason: String) : BootstrapEvent()

    // --- UI LAYER (PROGRAM-016/017/018/019/020) ---
    object WidgetRegistryStarted : BootstrapEvent()
    data class WidgetRegistered(val widgetId: String, val category: String) : BootstrapEvent()
    data class WidgetRemoved(val widgetId: String) : BootstrapEvent()
    data class WidgetPriorityChanged(val widgetId: String, val newPriority: Int) : BootstrapEvent()
    object DashboardBlueprintCreated : BootstrapEvent()
    object WidgetRegistryCompleted : BootstrapEvent()
    data class WidgetRegistryFailed(val reason: String) : BootstrapEvent()
    object DashboardGenerationStarted : BootstrapEvent()
    object WidgetOrderFinalized : BootstrapEvent()
    object RecommendationsGenerated : BootstrapEvent()
    object DashboardReadyForLayout : BootstrapEvent()
    object DashboardGenerationCompleted : BootstrapEvent()
    data class DashboardGenerationFailed(val reason: String) : BootstrapEvent()
    object LayoutGenerationStarted : BootstrapEvent()
    data class ResponsiveGridCreated(val columns: Int) : BootstrapEvent()
    object LayoutOptimized : BootstrapEvent()
    object RenderTreeGenerated : BootstrapEvent()
    object LayoutReady : BootstrapEvent()
    object LayoutGenerationCompleted : BootstrapEvent()
    data class LayoutGenerationFailed(val reason: String) : BootstrapEvent()
    object MotionEngineStarted : BootstrapEvent()
    object AnimationPlanGenerated : BootstrapEvent()
    object TransitionCompleted : BootstrapEvent()
    data class WidgetAnimationFinished(val widgetId: String) : BootstrapEvent()
    object DashboardAnimationReady : BootstrapEvent()
    object MotionEngineCompleted : BootstrapEvent()
    data class MotionEngineFailed(val reason: String) : BootstrapEvent()
    object DashboardRenderStarted : BootstrapEvent()
    object DashboardCreated : BootstrapEvent()
    data class WidgetRendered(val widgetId: String) : BootstrapEvent()
    object DashboardUpdated : BootstrapEvent()
    object IncrementalRenderCompleted : BootstrapEvent()
    object DashboardReady : BootstrapEvent()
    data class DashboardRenderFailed(val reason: String) : BootstrapEvent()

    // --- HIGH-LEVEL INTELLIGENCE EVENTS (PROGRAM-014) ---
    object NewResultsAvailable : BootstrapEvent()
    data class FeeBalanceChanged(val oldBalance: Double, val newBalance: Double) : BootstrapEvent()
    data class PaymentRecorded(val amount: Double) : BootstrapEvent()
    object RegistrationOpened : BootstrapEvent()
    object RegistrationClosed : BootstrapEvent()
    object NewTimetableAvailable : BootstrapEvent()
    object ExamScheduleUpdated : BootstrapEvent()
    object CatScheduleChanged : BootstrapEvent()
    data class LibraryDueSoon(val bookTitle: String, val daysRemaining: Int) : BootstrapEvent()
    data class LibraryOverdue(val bookTitle: String) : BootstrapEvent()
    object HostelInformationChanged : BootstrapEvent()
    data class NewAnnouncement(val title: String) : BootstrapEvent()
    data class NewDocumentAvailable(val docType: String) : BootstrapEvent()
    data class DashboardRefreshRequired(val scope: String) : BootstrapEvent()
    object StudentContextChanged : BootstrapEvent()

    // --- CONTEXT EVENT ENGINE INTERNAL LIFECYCLE (PROGRAM-014) ---
    object ContextEventCreated : BootstrapEvent()
    data class PriorityEventDispatched(val eventName: String, val priority: String) : BootstrapEvent()
    object DashboardRefreshPlanned : BootstrapEvent()
    data class NotificationGenerated(val notificationId: String) : BootstrapEvent()
    object ContextEventCompleted : BootstrapEvent()
    data class ContextEventFailed(val reason: String) : BootstrapEvent()
}
